### PR TITLE
adjust return status

### PR DESCRIPTION
**Pull request by drummerwolli**
second part of #39

### CODE REVIEW

**Comment by drummerwolli** [comment]
can we finally merge this?

**Comment by chutium** [comment]
let us wait for the next major spark version update, will be 2.0.0 then, and this change could be included in next major version update.

**Comment by drummerwolli** [comment]
any progress? @toarndt @oyilmaz @satybald @chutium ???

**Comment by satybald** [comment]
LGTM! thanks @drummerwolli.

**Pull request merged**
